/* =====================================================
   SA CAREER HUB V2.2
   COMPLETE SCRIPT
   ===================================================== */


/* =====================================================
   DARK MODE
   ===================================================== */

document.addEventListener("DOMContentLoaded", function () {

    // Load saved theme
    if (localStorage.getItem("theme") === "dark") {
        document.body.classList.add("dark-mode");
    }

});


/* =====================================================
   HOME SEARCH
   ===================================================== */

document.addEventListener("DOMContentLoaded", function () {

    const searchInput = document.getElementById("searchInput");
    const jobCards = document.querySelectorAll(".job-card");

    if (searchInput && jobCards.length > 0) {

        searchInput.addEventListener("keyup", function () {

            const value = searchInput.value.toLowerCase();

            jobCards.forEach(function (card) {

                const text = card.innerText.toLowerCase();

                if (text.includes(value)) {
                    card.style.display = "";
                } else {
                    card.style.display = "none";
                }

            });

        });

    }

});


/* =====================================================
   CAREER TIPS
   ===================================================== */

document.addEventListener("DOMContentLoaded", function () {

    const tips = [
        "Update your CV every month.",
        "Apply for jobs daily.",
        "Prepare for interviews before you are invited.",
        "Use a professional email address.",
        "Learn a new skill every week.",
        "Network on LinkedIn.",
        "Tailor your CV for every application.",
        "Always check application closing dates."
    ];

    const tipElement = document.getElementById("careerTip");

    if (tipElement) {

        let index = 0;

        tipElement.textContent = tips[index];

        setInterval(function () {

            index++;

            if (index >= tips.length) {
                index = 0;
            }

            tipElement.textContent = tips[index];

        }, 6000);

    }

});


/* =====================================================
   CV BUILDER
   ===================================================== */

document.addEventListener("DOMContentLoaded", function () {

    const downloadBtn = document.getElementById("downloadCV");

    if (downloadBtn) {

        downloadBtn.addEventListener("click", function () {

            const name =
                document.getElementById("name")?.value || "";

            const email =
                document.getElementById("email")?.value || "";

            const phone =
                document.getElementById("phone")?.value || "";

            const education =
                document.getElementById("education")?.value || "";

            const experience =
                document.getElementById("experience")?.value || "";

            const skills =
                document.getElementById("skills")?.value || "";

            const cv = `
SA CAREER HUB CV

==============================

Name:
${name}

Email:
${email}

Phone:
${phone}

Education:
${education}

Experience:
${experience}

Skills:
${skills}

Generated by SA Career Hub Version 2.2
`;

            const blob = new Blob([cv], {
                type: "text/plain"
            });

            const link = document.createElement("a");

            link.href = URL.createObjectURL(blob);
            link.download = "My_CV.txt";

            document.body.appendChild(link);

            link.click();

            document.body.removeChild(link);

            URL.revokeObjectURL(link.href);

        });

    }

});


/* =====================================================
   SAVED JOBS
   ===================================================== */

function getSavedJobs() {

    return JSON.parse(
        localStorage.getItem("savedJobs")
    ) || [];

}


function updateSavedCounter() {

    const counter =
        document.getElementById("savedCount");

    if (counter) {

        counter.textContent =
            getSavedJobs().length;

    }

}


function saveSavedJob(jobTitle) {

    let savedJobs = getSavedJobs();

    if (savedJobs.includes(jobTitle)) {

        alert("ℹ️ This job is already saved.");

        return;

    }

    savedJobs.push(jobTitle);

    localStorage.setItem(
        "savedJobs",
        JSON.stringify(savedJobs)
    );

    updateSavedCounter();

    alert("✅ Job saved successfully!");

}


function displaySavedJobs() {

    const savedJobsList =
        document.getElementById("savedJobsList");

    if (!savedJobsList) return;

    const savedJobs = getSavedJobs();

    savedJobsList.innerHTML = "";

    if (savedJobs.length === 0) {

        savedJobsList.innerHTML =
            "<li>No saved jobs yet.</li>";

        return;

    }

    savedJobs.forEach(function (job) {

        const li =
            document.createElement("li");

        li.textContent = job;

        savedJobsList.appendChild(li);

    });

}


function clearSavedJobs() {

    if (!confirm("Clear all saved jobs?")) {
        return;
    }

    localStorage.removeItem("savedJobs");

    displaySavedJobs();

    updateSavedCounter();

    alert("✅ Saved jobs cleared.");

}


/* =====================================================
   SAVE LEARNERSHIPS
   ===================================================== */

function getSavedLearnerships() {

    return JSON.parse(
        localStorage.getItem("savedLearnerships")
    ) || [];

}


function updateSavedLearnershipCounter() {

    const counter =
        document.getElementById(
            "savedLearnershipCount"
        );

    if (counter) {

        counter.textContent =
            getSavedLearnerships().length;

    }

}


function saveLearnership(title) {

    let savedLearnerships =
        getSavedLearnerships();

    if (savedLearnerships.includes(title)) {

        alert(
            "This learnership is already saved!"
        );

        return;

    }

    savedLearnerships.push(title);

    localStorage.setItem(
        "savedLearnerships",
        JSON.stringify(savedLearnerships)
    );

    updateSavedLearnershipCounter();

    alert(
        "✅ Learnership saved successfully!"
    );

}


function displaySavedLearnerships() {

    const savedList =
        document.getElementById(
            "savedLearnershipsList"
        );

    if (!savedList) return;

    const savedLearnerships =
        getSavedLearnerships();

    savedList.innerHTML = "";

    if (savedLearnerships.length === 0) {

        savedList.innerHTML =
            "<li>No saved learnerships yet.</li>";

        return;

    }

    savedLearnerships.forEach(function (learnership) {

        const li =
            document.createElement("li");

        li.textContent = learnership;

        savedList.appendChild(li);

    });

}


function clearSavedLearnerships() {

    if (!confirm(
        "Clear all saved learnerships?"
    )) {

        return;

    }

    localStorage.removeItem(
        "savedLearnerships"
    );

    displaySavedLearnerships();

    updateSavedLearnershipCounter();

    alert(
        "✅ Saved learnerships cleared!"
    );

}


/* =====================================================
   SAVE INTERNSHIPS
   ===================================================== */

function getSavedInternships() {

    return JSON.parse(
        localStorage.getItem("savedInternships")
    ) || [];

}


function updateSavedInternshipCounter() {

    const counter =
        document.getElementById(
            "savedInternshipCount"
        );

    if (counter) {

        counter.textContent =
            getSavedInternships().length;

    }

}


function saveInternship(title) {

    let savedInternships =
        getSavedInternships();

    if (savedInternships.includes(title)) {

        alert(
            "This internship is already saved!"
        );

        return;

    }

    savedInternships.push(title);

    localStorage.setItem(
        "savedInternships",
        JSON.stringify(savedInternships)
    );

    updateSavedInternshipCounter();

    alert(
        "✅ Internship saved successfully!"
    );

}


function displaySavedInternships() {

    const savedList =
        document.getElementById(
            "savedInternshipsList"
        );

    if (!savedList) return;

    const savedInternships =
        getSavedInternships();

    savedList.innerHTML = "";

    if (savedInternships.length === 0) {

        savedList.innerHTML =
            "<li>No saved internships yet.</li>";

        return;

    }

    savedInternships.forEach(function (internship) {

        const li =
            document.createElement("li");

        li.textContent = internship;

        savedList.appendChild(li);

    });

}


function clearSavedInternships() {

    if (!confirm(
        "Clear all saved internships?"
    )) {

        return;

    }

    localStorage.removeItem(
        "savedInternships"
    );

    displaySavedInternships();

    updateSavedInternshipCounter();

    alert(
        "✅ Saved internships cleared!"
    );

}


/* =====================================================
   JOB SEARCH + FILTERS
   ===================================================== */

document.addEventListener("DOMContentLoaded", function () {

    const searchInput =
        document.getElementById(
            "jobSearch"
        ) ||
        document.getElementById(
            "searchInput"
        );

    const provinceFilter =
        document.getElementById(
            "provinceFilter"
        );

    const categoryFilter =
        document.getElementById(
            "categoryFilter"
        );

    const jobs =
        document.querySelectorAll(
            ".job"
        );

    function filterJobs() {

        const searchValue =
            searchInput
                ? searchInput.value.toLowerCase()
                : "";

        const provinceValue =
            provinceFilter
                ? provinceFilter.value
                : "";

        const categoryValue =
            categoryFilter
                ? categoryFilter.value
                : "";

        jobs.forEach(function (job) {

            const text =
                job.innerText.toLowerCase();

            const province =
                job.dataset.province || "";

            const category =
                job.dataset.category || "";

            const matchesSearch =
                text.includes(searchValue);

            const matchesProvince =
                !provinceValue ||
                province === provinceValue;

            const matchesCategory =
                !categoryValue ||
                category === categoryValue;

            if (
                matchesSearch &&
                matchesProvince &&
                matchesCategory
            ) {

                job.style.display = "";

            } else {

                job.style.display = "none";

            }

        });

    }

    if (searchInput) {

        searchInput.addEventListener(
            "input",
            filterJobs
        );

    }

    if (provinceFilter) {

        provinceFilter.addEventListener(
            "change",
            filterJobs
        );

    }

    if (categoryFilter) {

        categoryFilter.addEventListener(
            "change",
            filterJobs
        );

    }

});


/* =====================================================
   LEARNERSHIP SEARCH + FILTERS
   ===================================================== */

document.addEventListener("DOMContentLoaded", function () {

    const searchInput =
        document.getElementById(
            "learnershipSearch"
        );

    const provinceFilter =
        document.getElementById(
            "learnershipProvince"
        );

    const categoryFilter =
        document.getElementById(
            "learnershipCategory"
        );

    const learnerships =
        document.querySelectorAll(
            ".learnership"
        );

    function filterLearnerships() {

        const searchValue =
            searchInput
                ? searchInput.value.toLowerCase()
                : "";

        const provinceValue =
            provinceFilter
                ? provinceFilter.value
                : "";

        const categoryValue =
            categoryFilter
                ? categoryFilter.value
                : "";

        learnerships.forEach(function (item) {

            const text =
                item.innerText.toLowerCase();

            const province =
                item.dataset.province || "";

            const category =
                item.dataset.category || "";

            const matchesSearch =
                text.includes(searchValue);

            const matchesProvince =
                !provinceValue ||
                province === provinceValue;

            const matchesCategory =
                !categoryValue ||
                category === categoryValue;

            if (
                matchesSearch &&
                matchesProvince &&
                matchesCategory
            ) {

                item.style.display = "";

            } else {

                item.style.display = "none";

            }

        });

    }

    if (searchInput) {

        searchInput.addEventListener(
            "input",
            filterLearnerships
        );

    }

    if (provinceFilter) {

        provinceFilter.addEventListener(
            "change",
            filterLearnerships
        );

    }

    if (categoryFilter) {

        categoryFilter.addEventListener(
            "change",
            filterLearnerships
        );

    }

});


/* =====================================================
   PAGE STARTUP
   ===================================================== */

document.addEventListener("DOMContentLoaded", function () {

    updateSavedCounter();

    updateSavedLearnershipCounter();

    updateSavedInternshipCounter();

    displaySavedJobs();

    displaySavedLearnerships();

    displaySavedInternships();


    /* CLEAR SAVED JOBS BUTTON */

    const clearJobsBtn =
        document.getElementById(
            "clearSavedJobsBtn"
        );

    if (clearJobsBtn) {

        clearJobsBtn.onclick =
            clearSavedJobs;

    }


    /* CLEAR SAVED LEARNERSHIPS BUTTON */

    const clearLearnershipsBtn =
        document.getElementById(
            "clearSavedLearnershipsBtn"
        );

    if (clearLearnershipsBtn) {

        clearLearnershipsBtn.onclick =
            clearSavedLearnerships;

    }


    /* CLEAR SAVED INTERNSHIPS BUTTON */

    const clearInternshipsBtn =
        document.getElementById(
            "clearSavedInternshipsBtn"
        );

    if (clearInternshipsBtn) {

        clearInternshipsBtn.onclick =
            clearSavedInternships;

    }

});
/* =====================================================
   SAVE BURSARIES
   ===================================================== */

function getSavedBursaries() {

    return JSON.parse(
        localStorage.getItem("savedBursaries")
    ) || [];

}


function saveBursary(title) {

    let savedBursaries =
        getSavedBursaries();

    if (savedBursaries.includes(title)) {

        alert(
            "This bursary is already saved!"
        );

        return;

    }

    savedBursaries.push(title);

    localStorage.setItem(
        "savedBursaries",
        JSON.stringify(savedBursaries)
    );

    alert(
        "✅ Bursary saved successfully!"
    );

}
function displaySavedBursaries() {

    const savedList =
        document.getElementById("savedBursariesList");

    if (!savedList) return;

    const savedBursaries =
        getSavedBursaries();

    savedList.innerHTML = "";

    if (savedBursaries.length === 0) {

        savedList.innerHTML =
            "<li>No saved bursaries yet.</li>";

        return;
    }

    savedBursaries.forEach(function (bursary) {

        const li =
            document.createElement("li");

        li.textContent = bursary;

        savedList.appendChild(li);

    });
}


function clearSavedBursaries() {

    if (!confirm(
        "Clear all saved bursaries?"
    )) {
        return;
    }

    localStorage.removeItem(
        "savedBursaries"
    );

    displaySavedBursaries();

    alert(
        "✅ Saved bursaries cleared!"
    );
}


document.addEventListener(
    "DOMContentLoaded",
    function () {

        displaySavedBursaries();

        const clearBursariesBtn =
            document.getElementById(
                "clearSavedBursariesBtn"
            );

        if (clearBursariesBtn) {

            clearBursariesBtn.onclick =
                clearSavedBursaries;

        }

    }
);
function updateDashboard() {

    const jobs = getSavedJobs().length;
    const learnerships = getSavedLearnerships().length;
    const internships = getSavedInternships().length;
   const bursaries = getSavedBursaries().length;

    const jobsBox = document.getElementById("dashboardSavedJobs");
    const learnershipsBox = document.getElementById("dashboardLearnerships");
    const internshipsBox = document.getElementById("dashboardInternships");
   const bursariesBox = document.getElementById("dashboardBursaries");

    if (jobsBox) jobsBox.textContent = jobs;
    if (learnershipsBox) learnershipsBox.textContent = learnerships;
    if (internshipsBox) internshipsBox.textContent = internships;
   if (bursariesBox) bursariesBox.textContent = bursaries;
}

document.addEventListener("DOMContentLoaded", function () {
    updateDashboard();
});
/* =====================================================
   APPLICATION TRACKER
   ===================================================== */

function getApplications() {
    return JSON.parse(localStorage.getItem("applications")) || [];
}

function applyForOpportunity(title) {

    let applications = getApplications();

    if (applications.includes(title)) {
        alert("You have already applied for this opportunity.");
        return;
    }

    applications.push(title);

    localStorage.setItem(
        "applications",
        JSON.stringify(applications)
    );

    updateApplicationsCounter();

    alert("✅ Application tracked successfully!");
}

function displayApplications() {

    const list = document.getElementById("applicationsList");

    if (!list) return;

    const applications = getApplications();

    list.innerHTML = "";

    if (applications.length === 0) {
        list.innerHTML = "<li>No applications tracked yet.</li>";
        return;
    }

    applications.forEach(function(item) {
        const li = document.createElement("li");
        li.textContent = item;
        list.appendChild(li);
    });
}

function clearApplications() {

    if (!confirm("Clear all tracked applications?")) {
        return;
    }

    localStorage.removeItem("applications");

    displayApplications();

    updateApplicationsCounter();

    alert("✅ Applications cleared!");
}

function updateApplicationsCounter() {

    const counter = document.getElementById("dashboardApplications");

    if (counter) {
        counter.textContent = getApplications().length;
    }
}

document.addEventListener("DOMContentLoaded", function () {

    updateApplicationsCounter();

    displayApplications();

    const btn = document.getElementById("clearApplicationsBtn");

    if (btn) {
        btn.onclick = clearApplications;
    }

});
/* =====================================================
   ADMIN PANEL
   ===================================================== */

function getAdminJobs() {
    return JSON.parse(localStorage.getItem("adminJobs")) || [];
}

function addJob() {

    const title = document.getElementById("jobTitle").value.trim();
    const company = document.getElementById("jobCompany").value.trim();
    const location = document.getElementById("jobLocation").value.trim();

    if (!title || !company || !location) {
        alert("Please complete all fields.");
        return;
    }

    let jobs = getAdminJobs();

    jobs.push({
        title: title,
        company: company,
        location: location
    });

    localStorage.setItem(
        "adminJobs",
        JSON.stringify(jobs)
    );

    document.getElementById("jobTitle").value = "";
    document.getElementById("jobCompany").value = "";
    document.getElementById("jobLocation").value = "";

    displayAdminJobs();

    alert("✅ Job added successfully!");
}

function displayAdminJobs() {

    const list = document.getElementById("adminJobsList");

    if (!list) return;

    const jobs = getAdminJobs();

    list.innerHTML = "";

    if (jobs.length === 0) {

        list.innerHTML = "<li>No jobs added yet.</li>";

        return;
    }

    jobs.forEach(function(job, index) {

        const li = document.createElement("li");

        li.innerHTML =
    "<strong>" + job.title + "</strong><br>" +
    job.company + "<br>" +
    job.location +
    "<br><br>" +

    "<button onclick='editAdminJob(" + index + ")'>✏️ Edit</button> " +

    "<button onclick='deleteAdminJob(" + index + ")'>🗑️ Delete</button>";

        list.appendChild(li);

    });

}

function deleteAdminJob(index) {

    let jobs = getAdminJobs();

    if (!confirm("Delete this job?")) {
        return;
    }

    jobs.splice(index, 1);

    localStorage.setItem("adminJobs", JSON.stringify(jobs));

    displayAdminJobs();
    displayWebsiteJobs();
}
function editAdminJob(index) {

    const jobs = getAdminJobs();

    document.getElementById("jobTitle").value = jobs[index].title;
    document.getElementById("jobCompany").value = jobs[index].company;
    document.getElementById("jobLocation").value = jobs[index].location;

    deleteAdminJob(index);
}
document.addEventListener("DOMContentLoaded", function () {
    displayAdminJobs();
});

/* =====================================================
   SHOW ADMIN JOBS ON JOBS PAGE
   ===================================================== */

function displayWebsiteJobs() {

    const container = document.getElementById("adminJobsContainer");

    if (!container) return;

    const jobs = getAdminJobs();

    container.innerHTML = "";

    if (jobs.length === 0) {
        container.innerHTML = "<p>No admin jobs available yet.</p>";
        return;
    }

    jobs.forEach(function(job) {

        const card = document.createElement("div");

        card.className = "card";

        card.innerHTML = `
            <h3>${job.title}</h3>
            <p><strong>Company:</strong> ${job.company}</p>
            <p><strong>Location:</strong> ${job.location}</p>

         <button onclick="saveSavedJob('${job.title}')">
    ❤️ Save Job
</button>

            <button onclick="applyForOpportunity('${job.title}')">
                📩 Apply
            </button>
        `;

        container.appendChild(card);

    });

}

document.addEventListener("DOMContentLoaded", function () {
    displayWebsiteJobs();
});
