/* =====================================================
   SA CAREER HUB V2.2
   PART 1
   - App Start
   - Dark Mode
   - Home Search
   - Career Tips
   - CV Builder
===================================================== */

document.addEventListener("DOMContentLoaded", () => {

    console.log("✅ SA Career Hub Version 2.2 Started");

    /* ==========================================
       DARK MODE
    ========================================== */

    const darkModeBtn =
        document.getElementById("darkModeBtn") ||
        document.getElementById("darkMode");

    if (darkModeBtn) {

        // Load saved theme
        if (localStorage.getItem("theme") === "dark") {
            document.body.classList.add("dark-mode");
        }

        darkModeBtn.addEventListener("click", () => {

            document.body.classList.toggle("dark-mode");

            if (document.body.classList.contains("dark-mode")) {
                localStorage.setItem("theme", "dark");
            } else {
                localStorage.setItem("theme", "light");
            }

        });

    }

    /* ==========================================
       HOME SEARCH
    ========================================== */

    const searchInput = document.getElementById("searchInput");
    const jobCards = document.querySelectorAll(".job-card");

    if (searchInput && jobCards.length > 0) {

        searchInput.addEventListener("keyup", () => {

            const value = searchInput.value.toLowerCase();

            jobCards.forEach(card => {

                const text = card.innerText.toLowerCase();

                if (text.includes(value)) {
                    card.style.display = "";
                } else {
                    card.style.display = "none";
                }

            });

        });

    }

    /* ==========================================
       CAREER TIPS
    ========================================== */

    const tips = [

        "Update your CV every month.",

        "Apply for jobs daily.",

        "Prepare for interviews before you are invited.",

        "Use a professional email address.",

        "Learn a new skill every week.",

        "Network on LinkedIn.",

        "Tailor your CV for every application.",

        "Always check application closing dates."

    ];

    const tipElement = document.getElementById("careerTip");

    if (tipElement) {

        let index = 0;

        tipElement.textContent = tips[index];

        setInterval(() => {

            index++;

            if (index >= tips.length) {
                index = 0;
            }

            tipElement.textContent = tips[index];

        }, 6000);

    }

    /* ==========================================
       CV BUILDER
    ========================================== */

    const downloadBtn = document.getElementById("downloadCV");

    if (downloadBtn) {

        downloadBtn.addEventListener("click", () => {

            const name =
                document.getElementById("name")?.value || "";

            const email =
                document.getElementById("email")?.value || "";

            const phone =
                document.getElementById("phone")?.value || "";

            const education =
                document.getElementById("education")?.value || "";

            const experience =
                document.getElementById("experience")?.value || "";

            const skills =
                document.getElementById("skills")?.value || "";

            const cv = `

SA CAREER HUB CV

==============================

Name:
${name}

Email:
${email}

Phone:
${phone}

Education:
${education}

Experience:
${experience}

Skills:
${skills}

Generated by SA Career Hub Version 2.2

`;

            const blob = new Blob([cv], {
                type: "text/plain"
            });

            const link = document.createElement("a");

            link.href = URL.createObjectURL(blob);

            link.download = "My_CV.txt";

            document.body.appendChild(link);

            link.click();

            document.body.removeChild(link);

            URL.revokeObjectURL(link.href);

        });

    }

});
/* ==========================================
   PART 2A - SAVE JOBS SYSTEM
========================================== */

function getSavedJobs() {
    return JSON.parse(localStorage.getItem("savedJobs")) || [];
}

function updateSavedCounter() {
    const counter = document.getElementById("savedCount");

    if (counter) {
        counter.textContent = getSavedJobs().length;
    }
}

function saveSavedJob(jobTitle) {

    let savedJobs = getSavedJobs();

    if (!savedJobs.includes(jobTitle)) {
        savedJobs.push(jobTitle);
        localStorage.setItem("savedJobs", JSON.stringify(savedJobs));
        alert("✅ Job saved successfully!");
    } else {
        alert("ℹ️ This job is already saved.");
    }

    updateSavedCounter();
}

document.addEventListener("DOMContentLoaded", () => {
    updateSavedCounter();
});
/* ==========================================
   PART 2B - SAVED JOBS PAGE
========================================== */

function displaySavedJobs() {

    const savedJobsList = document.getElementById("savedJobsList");

    if (!savedJobsList) return;

    savedJobsList.innerHTML = "";

    const savedJobs = getSavedJobs();

    if (savedJobs.length === 0) {

        savedJobsList.innerHTML =
            "<li>No saved jobs yet.</li>";

        return;
    }

    savedJobs.forEach(job => {

        const li = document.createElement("li");

        li.textContent = job;

        savedJobsList.appendChild(li);

    });

}

document.addEventListener("DOMContentLoaded", () => {

    displaySavedJobs();

    const clearBtn =
        document.getElementById("clearSavedJobsBtn");

    if (clearBtn) {

        clearBtn.addEventListener("click", () => {

            if (confirm("Clear all saved jobs?")) {

                localStorage.removeItem("savedJobs");

                displaySavedJobs();

                updateSavedCounter();

                alert("✅ Saved jobs cleared.");

            }

        });

    }

});
// ===============================
// SAVE INTERNSHIP
// ===============================

function saveInternship(title) {
    let savedInternships = JSON.parse(localStorage.getItem("savedInternships")) || [];

    if (savedInternships.includes(title)) {
        alert("This internship is already saved!");
        return;
    }

    savedInternships.push(title);
    localStorage.setItem("savedInternships", JSON.stringify(savedInternships));

    alert("Internship saved successfully!");
}
// ===============================
// SAVED INTERNSHIP COUNTER
// ===============================

function updateSavedInternshipCounter() {
    const counter = document.getElementById("savedInternshipCount");

    if (counter) {
        const savedInternships =
            JSON.parse(localStorage.getItem("savedInternships")) || [];

        counter.textContent = savedInternships.length;
    }
}

document.addEventListener("DOMContentLoaded", () => {
    updateSavedInternshipCounter();
});
